docs/contribute/markdown-reference.md, static/api/v0/openapi.yaml, versioned_docs/version-v0/contribute/markdown-reference.md, yarn.lock
=> add new endpoints specs

docusaurus.config.js, static/api/v0/events.json, versioned_sidebars/version-v0-sidebars.json
=> Add events API

docusaurus.config.js
=> Change version names

src/css/custom.css, src/pages/index.js
=> Update background color. Remove homepage

static/api/v1/openapi.yaml
Adding SCIM V1 to the docs + other updates since this change
=> Add SCIM to openapi

docs/release-notes/console-release-notes.mdx, docs/release-notes/endpoint-release-notes.mdx, docs/tools/policy-simulation.mdx, sidebars.js
=> Week of march 10 updates

docs/auth-sso/auth-sso.mdx, docs/auth-sso/identity-providers.mdx, docs/deployment/authenticators.mdx, docs/deployment/branding.mdx, docs/deployment/deployment.mdx, docs/directory/directory-integrations.mdx, docs/directory/directory.mdx, docs/directory/groups.mdx, docs/directory/identities.mdx, docs/includes/_app-scheme-caution.mdx, docs/includes/_bind-delivery-method-email-diagram.mdx, docs/includes/_bind-delivery-method-return-diagram.mdx, docs/includes/_bind-passkey-backend-general.mdx, docs/includes/_bind-passkey-frontend-email.mdx, docs/includes/_bind-passkey-frontend-return.mdx, docs/includes/_deeplinking-native-sdk.mdx, docs/includes/_passkey-binding-methods.mdx, docs/includes/_passkeys-and-devices-overview.mdx, docs/installation/installation.mdx, docs/introduction/faq.mdx, docs/introduction/introduction.mdx, docs/introduction/universal-passkeys.mdx, docs/introduction/what-does-sw-do.mdx, docs/inventory/endpoint-integrations.mdx, docs/release-notes/console-release-notes.mdx, docs/release-notes/endpoint-release-notes.mdx, docs/tools/assessments.mdx, sidebars.js
=> Week of march 18 updates

docs/inventory/device-query.mdx, src/components/Arcade.tsx
Added arcades. Additional arcades will be added for query results at a later time. My environment isn't pulling any device data.
Thank you!
=> Updated device query based on UX changes

docs/directory/directory.mdx, docs/tools/integration-catalog/crowdstrike.mdx, docs/tools/integration-catalog/integration-catalog.mdx, docs/tools/tools.mdx, sidebars.js, src/components/Arcade.tsx
Added crowdstrike integration steps.
Thank you!
=> Added crowdstrike integration steps

docs/tools/integration-catalog/jamf.mdx, sidebars.js, src/components/Arcade.tsx
=> Jamf integration

docs/product-guides/zero-trust-authentication.mdx
Updated content and steps for zta
Thank you!
=> Updated content and steps for zta

docs/product-guides/device360.mdx
Since we decided we needed to remove the option to try it for free, changed the action phrase to See it in action so it will apply to demos.
Thank you!
=> Changed wording away from free

docs/directory/roles.mdx, sidebars.js, src/components/Arcade.tsx
Added current content for roles
Thank you!
=> Added current content for roles

docs/tools/policy.mdx
=> Secure access policy updates

docs/auth-and-sso/product-integration-guides/okta.mdx, docs/directory/directory-integrations/okta.mdx, docs/tools/integrations/crowdstrike.mdx, docs/tools/integrations/jamf.mdx
=> Identified color coding section as a legend to clear up confusion from internal stakeholders

docs/access-control/identity-providers/okta.mdx, package.json
- Updated guide for Okta
- Included new section for Routing rule
Thank you!
=> Okta Integration guide update

docs/access-control/applications/microsoft-eam.mdx, docs/access-control/identity-providers/microsoft-eam.mdx, sidebars.js
- Added new file for Microsoft EAM integration guide
- Updated sidebar nav file for new guide
Thank you!
=> New guide for Microsoft External Authentication Methods (EAM)

docs/access-control/applications/microsoft-eam.mdx
- Revised intro section
- Updated language around Entra ID
Thank you!
=> Microsoft EAM guide updates

docs/release-notes/endpoint.mdx
- Update Secure Access Endpoint release notes page with 2.100.5
Thank you!
=> Update sa endpoint release notes page with 2.100.5

docs/access-control/applications/microsoft-eam.mdx
- Fixed value for step
Thank you!
=> Resolved mislabeled step value

docs/tools/integrations/crowdstrike.mdx
- Revised and updated CrowdStrike integration guide
Thank you!
=> Revamp crowdstrike integration guide

docs/tools/integrations/crowdstrike.mdx, docs/tools/integrations/jamf.mdx
- Revised jamf integration guide updated
Thank you!
=> Revised jamf integration guide updated

docs/tools/integrations/crowdstrike.mdx, docs/tools/integrations/intune.mdx, docs/tools/integrations/jamf.mdx, sidebars.js
- Added new guide for Intune integrations
- Included new document in sidebar nav file
Thank you!
=> Intune integerations guide addition

docs/access-control/applications/ws-fed.mdx, sidebars.js
- New WS-Fed guide added for Applications documents
- Updated sidebar to include new guide
Thank you!
=> Add new wsfed guide, update sidebar

docs/access-control/applications/microsoft-eam.mdx
- Added section to address matching `objectid` and `externalid` values for potential issue with missing EAM for users
Thank you!
=> Resolve Content Issue #196 for EAM

docs/access-control/applications/applications.mdx, docs/access-control/applications/microsoft-eam.mdx, docs/access-control/applications/onelogin.mdx, docs/access-control/applications/ws-fed.mdx
- Revised app guides to include generic SCIM information, updated links
Thank you!
=> Revised app guides to include generic SCIM information, updated links

docs/access-control/applications/applications.mdx, docs/tools/tools.mdx
- Clean up tools landing page
- Revised language on apps landing page
Thank you!
=> Clean up tools landing page, revised language on apps

docs/access-control/applications/okta.mdx
- Consolidated previous Okta directory integrations steps into new section for Okta app guide
- Reused existing arcade clips for media
Thank you!
=> Add okta SCIM steps to okta app guide

docs/access-control/applications/microsoft-eam.mdx
- Updated EAM page to show correct step for section
=> Revise step 9 for set up bi console section

static/api/v0/openapi.yaml
- Fix schema for SCIMListAllUsers in v0 API docs
Thank you!
=> Revise scimlistallusers api schema

static/api/v0/openapi.yaml
- Revise nested schema in SCIMUser endpoints for Secure Work
Thank you!
=> Fix nested schema configuration for SCIM endpoints in v0

static/api/v0/openapi.yaml
- Fix nested parameters for post and patch SCIM group endpoints"
Thank you!
=> Fix group SCIM request parameters for v0 API docs

docs/release-notes/endpoint.mdx
- Update Release Notes and Changelog page for Secure Access
- Console v1.53.0 updates
Thank you!
=> 20250123 release notes and changelog

docs/release-notes/endpoint.mdx
- Fixed formatting and removed changelog items
Thank you!
=> Clearing changelog and keeping format

docs/access-control/applications/okta.mdx
- Revised the Okta integration guide for updated instructions and details
Thank you!
=> Overhaul revision of Okta integration guide

docs/access-control/applications/ws-fed.mdx
=> Overhaul WSFed Documentation

docs/access-control/applications/okta.mdx
- Revise header reference for Configure inbound provisioning
- Relocate SCIM callout for Beyond Identity
Thank you!
=> Okta guide fixes

docs/access-control/applications/okta.mdx
- Add SCIM callout for Okta section II
=> Add SCIM callout for Okta section II

docs/directory/directory.mdx
- Updated Directory landing page with more info
Thank you!
=> Add relevant information to directory landing page

docs/access-control/applications/okta.mdx, docs/access-control/applications/ws-fed.mdx
=> wsfed and okta changes

docs/access-control/applications/ws-fed.mdx
=> PE-7313: Update docs for powershell updates

docs/directory/groups.mdx, docs/directory/identities.mdx
- Update Identities and Groups pages for Directory docs
Thank you!
=> Update Identities and Groups models documentation for directory

docs/access-control/applications/ws-fed.mdx
=> Note about powershell version

docusaurus.config.js
- Update top navigation bar with links to Home and API Reference for v1
Thank you!
=> Update nav bar with home and api ref links

docusaurus.config.js
- Update "Next Gen" to "Secure Access" for docs dropdown menu
Thank you!
=> Rename docs dropdown menu

docs/access-control/applications/onelogin.mdx
- Revise OneLogin guide
- Add SCIM section
- Fix typos
- Include JSON template
Thank you!
=> Revise OneLogin guide

docs/access-control/applications/onelogin.mdx, docs/resources/pa-support.mdx, sidebars.js, static/api/v0/openapi.yaml
=> Platform Authenticator support guideline doc

docs/end-user-guides/end-user-guides.mdx, docs/end-user-guides/proxy-end-user.mdx, docs/introduction.mdx, docs/release-notes/endpoint.mdx, sidebars.js
- Fixed intro quick link on home page
- Created new End User section
- Moved existing Proxy guide
- Updated related links to guide
Thank you!
=> Add new section, update links

static/api/v1/openapi.yaml
Fixes issues with SSO Configs section in our v1 API docs. They still need to be standardized, but nothing is urgent at the moment.
Thank you!
=> PE-8156: Fix errors with SSO Configs in our Public Docs

docs/end-user-guides/self-enrollment.mdx
=> fix alignment

docs/release-notes/endpoint.mdx
=> release notes

docs/integrations/integrations-logs.mdx, docs/integrations/logs/logs.mdx, docs/integrations/logs/mdm-edr.mdx, docs/integrations/logs/siem.mdx, sidebars.js
Closes [this ticket](https://linear.app/byid/issue/DOCS-3/end-user-guide-explaining-how-ike-can-use-the-new-integrations-log)
1. Adds an Integrations Logs summary section
2. Adds an mdm/edr Logs section
3. Adds a siem Logs section placeholder
=> DOCS-3 Integrations Logs

docs/release-notes/endpoint.mdx
=> Release Notes for Android 2.103.1

docs/access-control/applications/applications.mdx, docs/access-control/applications/realitycheck-for-teams.mdx, docs/access-control/applications/realitycheck-for-zoom.mdx, sidebars.js
=> PROD-13: RC on Secure Access

docs/release-notes/endpoint.mdx
=> add endpoint notes

docs/release-notes/endpoint.mdx
Needed to fix version number for a release note. 
Thank you!
=> Fix version number

docs/release-notes/endpoint.mdx
Release notes for Secure Access also needed to also mention the Kandji Integration. 
Thank you!
=> Adding Kandji integration information to the release notes

static/api/v0/openapi.yaml
Updates SCIM v0 api docs for the new `employeeNumber` user attribute.
=> feat(scim): update v0 docs for scim api changes.

docs/release-notes/endpoint.mdx
These are the release notes for June 14, to be published with the monolithic release. 
Thank you!
=> June 14 Release Notes for Secure Access

docs/release-notes/endpoint.mdx
Needed to update the verbiage on an items of the release notes. 
Thank you!
=> Update verbiage for release notes

docs/directory/manage-users/add-users.md, docs/directory/manage-users/delete-users.md, docs/directory/manage-users/revoke-user-passkey.md, docs/directory/manage-users/suspend-users.md
Added new documentation related to User Management. Also, I updated our June 14 release notes to remove items that didn't make it to production with the monolithic release. 
Thank you!
=> New User Management Docs, plus updates to June 14 release notes

docs/release-notes/endpoint.mdx
These are the release notes for the new PA release (version 2.104.0). 
Thank you!
=> New release notes for PA release on June 24 2025

docs/directory/manage-identities/add-users.mdx, docs/directory/manage-identities/delete-users.mdx
Fixed two typos I spotted. 
Thank you!
=> Fixed two typos.

docs/directory/roles.mdx
Trying to see why the new section for RBAC is not rendering. 
Thank you!
=> New RBAC section not showing on the page

docs/end-user-guides/proxy-end-user.mdx, docs/end-user-guides/self-enrollment.mdx
=> Edit article slug

sidebars.js
=> Improve left-hand navigation

docs/release-notes/endpoint.mdx
Release Notes for Secure Access on July 23, 2025 (as part of the monolithic release)
Thank you!
=> July19 release notes

static/api/v0/openapi.yaml
Add Example PATCH request to PATCH users in SW API docs
=> DOCS-96: Add Example PATCH request to PATCH users in SW API docs

docs/end-user-guides/extend-passkey-credential/extend-credential-macos.mdx, docs/end-user-guides/extend-passkey-credential/extend-credential-windows.mdx
Updates to articles. 
Thank you!
=> Updates to articles

docs/passkey-lifecycle/how-passkeys-are-handled.mdx, sidebars.js
New article for SA: How Passkeys Are Handled on Mobile and Desktop Devices
Thank you!
=> New article: How Passkeys Are Handled on Mobile and Desktop Devices

docusaurus.config.js, static/api/v1/openapi.yaml
https://linear.app/byid/issue/DOCS-103/document-secure-access-api-endpoints-for-the-fedramp-environment
=> DOCS-103: Add env specific urls to docs

docs/end-user-guides/self-enrollment.mdx, docs/resources/platform-information/session-behavior.mdx
Updates to docs based on Linear Tickets: DOCS-80 and DOCS-74
Thank you!
=> Updates to docs based on Linear Tickets: DOCS-80 and DOCS-74

docs/integrations/crowdstrike.mdx, docs/integrations/intune.mdx, docs/integrations/jamf.mdx, docs/release-notes/endpoint.mdx
Linear DOCS-88 Updates 
Thank you!
=> Updates aug12

docs/introduction.mdx
Fix bullet point on landing page
Thank you!
=> Fix bullet point on intro page

static/api/v0/openapi.yaml, static/api/v1/openapi.yaml
Fix Identity Provider openapi spec + Distinguish Secure Workforce vs Secure Access API
=> DOCS-110: Fix Identity Provider openapi spec + Distinguish Secure Workforce vs Secure Access API

static/api/v0/openapi.yaml
=> DOCS-126: Update V0 Public API Docs with GET /v2/binding-jobs endpoint

docs/release-notes/endpoint.mdx
Add one more item to release notes 
Thank you!
=> Add one more item to the release notes

docs/directory/manage-identities/add-users.mdx
Add enrollment status information
Thank you!
=> Added enrollment statuses information

docs/resources/platform-information/session-behavior.mdx
=> Add session behavior from release notes to main doc

docs/resources/platform-information/session-behavior.mdx
=> improved the spacing

docs/release-notes/endpoint.mdx, src/css/custom.css
=> PA release notes

docs/release-notes/endpoint.mdx
=> Hot Fix -- PA Android

docs/release-notes/endpoint.mdx
=> Android PA Hot Fix

docs/release-notes/endpoint.mdx
=> Added missing word
